name: todo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  flutter_adaptive_scaffold: ^0.1.6
  table_calendar: ^3.0.9
  uuid: ^3.0.7
  either_dart: ^1.0.0
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
