name: todo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^10.2.0
  flutter_adaptive_scaffold: ^0.1.7
  table_calendar: ^3.0.9
  uuid: ^4.0.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shimmer_animation: ^2.1.0+1
  args: ^2.4.2
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
